name: geoflutterfire2
description: GeoFlutterFire2 is an open-source library that allows you to store and query firestore documents based on their geographic location.
version: 2.3.13
homepage: https://github.com/beerstorm-net/geoflutterfire2

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^4.0.4
  rxdart: ^0.27.5

dev_dependencies:
  flutter_test:
    sdk: flutter
